FROM ubuntu:26.04
RUN apt-get update && \
    apt-get install --no-install-recommends -y \
        ca-certificates \
        curl \
        jq \
        openssl \
        wget \
        yq && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /root
