name: Build and Push Docker Image

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
  schedule:
  - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on:
      group: Default
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Log in to Quay.io
        if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' }}
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Heavy - Extract metadata
        id: meta-heavy
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        with:
          images: quay.io/cyclops-k8s/swiss-army-knife
          tags: |
            type=raw,value=heavy-latest
            type=sha,prefix=heavy-sha-
            type=schedule,pattern=heavy-{{date 'YYYYMMDD'}}

      - name: Heavy - Build and push Docker image
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: .
          file: Dockerfile.heavy
          labels: ${{ steps.meta-heavy.outputs.labels }}
          push: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' }}
          tags: ${{ steps.meta-heavy.outputs.tags }}

      - name: Lite - Extract metadata
        id: meta-lite
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        with:
          images: quay.io/cyclops-k8s/swiss-army-knife
          tags: |
            type=raw,value=lite-latest
            type=sha,prefix=lite-sha-
            type=schedule,pattern=lite-{{date 'YYYYMMDD'}}

      - name: Lite - Build and push Docker image
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: .
          file: Dockerfile.lite
          labels: ${{ steps.meta-lite.outputs.labels }}
          push: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' }}
          tags: ${{ steps.meta-lite.outputs.tags }}
